on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, macos-10.15, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - run: cat darwin-atomic-test.nix
      - run: nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/6de161729c81dc98e844793cc9c8fda29d5ef62a.tar.gz darwin-atomic-test.nix
      - run: ./result/test
